# Generated by Django 6.0 on 2026-02-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="sentiment_score",
            field=models.FloatField(default=0.0),
        ),
    ]
